


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."accomplishment_entries" (
    "entry_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text",
    "description" "text",
    "venue" "text",
    "participation" "text",
    "author" "text",
    "start_date" "date",
    "end_date" "date",
    "report_id" bigint,
    "form_type_id" bigint
);


ALTER TABLE "public"."accomplishment_entries" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."accomplishment_reports" (
    "report_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "start_date" "date",
    "end_date" "date",
    "date_submitted" "date",
    "status" "text",
    "remarks" "text",
    "faculty_id" bigint
);


ALTER TABLE "public"."accomplishment_reports" OWNER TO "postgres";


ALTER TABLE "public"."accomplishment_reports" ALTER COLUMN "report_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."accomplishment_entries_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."accomplishment_entries" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."accomplishment_entries_entry_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."departments" (
    "department_id" bigint NOT NULL,
    "department_name" "text",
    "college_name" "text"
);


ALTER TABLE "public"."departments" OWNER TO "postgres";


ALTER TABLE "public"."departments" ALTER COLUMN "department_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."department_department_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."export_records" (
    "export_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "filter_used" "text",
    "format" "text",
    "generated_by" bigint
);


ALTER TABLE "public"."export_records" OWNER TO "postgres";


ALTER TABLE "public"."export_records" ALTER COLUMN "export_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."export_records_export_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."faculties" (
    "faculty_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "username" "text",
    "first_name" "text",
    "last_name" "text",
    "email" "text",
    "employment_type" "text",
    "department_id" bigint
);


ALTER TABLE "public"."faculties" OWNER TO "postgres";


ALTER TABLE "public"."faculties" ALTER COLUMN "faculty_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."faculties_faculty_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."form_types" (
    "form_type_id" bigint NOT NULL,
    "form_name" "text"
);


ALTER TABLE "public"."form_types" OWNER TO "postgres";


ALTER TABLE "public"."form_types" ALTER COLUMN "form_type_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."form_types_form_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."isip_authorship_forms" (
    "entry_id" bigint NOT NULL,
    "material_title" "text",
    "author" "text",
    "year" "date",
    "attachments" "text",
    "remarks" "text",
    "related_kras" "text"
);


ALTER TABLE "public"."isip_authorship_forms" OWNER TO "postgres";


ALTER TABLE "public"."isip_authorship_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."isip_authorship_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."isip_awards_forms" (
    "entry_id" bigint NOT NULL,
    "type" "text",
    "award" "text",
    "source" "text",
    "details" "text",
    "start_date" "date",
    "end_date" "date",
    "attachments" "text",
    "remarks" "text",
    "related_kras" "text"
);


ALTER TABLE "public"."isip_awards_forms" OWNER TO "postgres";


ALTER TABLE "public"."isip_awards_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."isip_awards_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."isip_creative_work_forms" (
    "entry_id" bigint NOT NULL,
    "creative_work_title" "text",
    "other_type" "text",
    "event_start_date" "date",
    "event_end_date" "date",
    "research_proof" "text",
    "remarks" "text",
    "related_kras" "text"
);


ALTER TABLE "public"."isip_creative_work_forms" OWNER TO "postgres";


ALTER TABLE "public"."isip_creative_work_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."isip_creative_work_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."isip_extension_programs_forms" (
    "entry_id" bigint NOT NULL,
    "extension_title" "text",
    "training_courses" "text",
    "external_clients_technical" "text",
    "information_dissemination" "text",
    "external_clients_consultancy" "text",
    "community_outreach" "text",
    "knowledge_transfer" "text",
    "organizing" "text",
    "work_scope" "text",
    "start_date" "date",
    "end_date" "date",
    "target_beneficiary_group" "text",
    "program_description" "text",
    "remarks" "text"
);


ALTER TABLE "public"."isip_extension_programs_forms" OWNER TO "postgres";


ALTER TABLE "public"."isip_extension_programs_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."isip_extension_programs_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."isip_oral_forms" (
    "entry_id" bigint NOT NULL,
    "paper_title" "text",
    "presentation_type" "text",
    "event_type" "text",
    "attachments" "text",
    "remarks" "text",
    "related_kras" "text"
);


ALTER TABLE "public"."isip_oral_forms" OWNER TO "postgres";


ALTER TABLE "public"."isip_oral_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."isip_oral_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."isip_other_accomplishments_forms" (
    "entry_id" bigint NOT NULL,
    "activity_title" "text",
    "start_date" "date",
    "end_date" "date",
    "participation" "text",
    "venue" "text",
    "attachments" "text",
    "remarks" "text",
    "related_kras" "text"
);


ALTER TABLE "public"."isip_other_accomplishments_forms" OWNER TO "postgres";


ALTER TABLE "public"."isip_other_accomplishments_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."isip_other_accomplishments_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."isip_partnership_forms" (
    "entry_id" bigint NOT NULL,
    "partnership_title" "text",
    "training_courses" "text",
    "advisory_service" "text",
    "information_dissemination" "text",
    "consultancy" "text",
    "community_outreach" "text",
    "knowledge_transfer" "text",
    "organizing_events" "text",
    "remarks" "text"
);


ALTER TABLE "public"."isip_partnership_forms" OWNER TO "postgres";


ALTER TABLE "public"."isip_partnership_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."isip_partnership_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."isip_patents_forms" (
    "entry_id" bigint NOT NULL,
    "attachments" "text",
    "remarks" "text"
);


ALTER TABLE "public"."isip_patents_forms" OWNER TO "postgres";


ALTER TABLE "public"."isip_patents_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."isip_patents_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."isip_publication_forms" (
    "entry_id" bigint NOT NULL,
    "publication_type" "text",
    "publication_title" "text",
    "publication_author" "text",
    "publication_date_published" "date",
    "publication_name" "text",
    "isi" "text",
    "scopus" "text",
    "pubmed" "text",
    "ched_recognized" "text",
    "peer_reviewed" "text",
    "other_reputable_database" "text",
    "publication_proof" "text",
    "remarks" "text",
    "related_kras" "text"
);


ALTER TABLE "public"."isip_publication_forms" OWNER TO "postgres";


ALTER TABLE "public"."isip_publication_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."isip_publications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."isip_research_forms" (
    "entry_id" bigint NOT NULL,
    "research_title" "text",
    "research_type" "text",
    "start_date" "date",
    "end_date" "date",
    "researcher_name" "text",
    "research_grant" numeric,
    "funding_amount" numeric,
    "total_funding" numeric,
    "other_fund_source" "text",
    "attachments" "text",
    "remarks" "text",
    "related_kras" "text"
);


ALTER TABLE "public"."isip_research_forms" OWNER TO "postgres";


ALTER TABLE "public"."isip_research_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."isip_research_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."isip_trainings_forms" (
    "entry_id" bigint NOT NULL,
    "activity_type" "text",
    "training_title" "text",
    "venue" "text",
    "start_date" "date",
    "end_date" "date",
    "attachments" "text",
    "remarks" "text",
    "related_kras" "text"
);


ALTER TABLE "public"."isip_trainings_forms" OWNER TO "postgres";


ALTER TABLE "public"."isip_trainings_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."isip_trainings_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pbms_creative_work_forms" (
    "entry_id" bigint NOT NULL,
    "linked_research" "text",
    "output_type" "text",
    "public_event_type" "text",
    "event_type" "text",
    "organizer_name" "text",
    "event_scope" "text",
    "event_venue" "text",
    "date_released" "date",
    "utilization_research_output" "text",
    "utilization_proof" "text"
);


ALTER TABLE "public"."pbms_creative_work_forms" OWNER TO "postgres";


ALTER TABLE "public"."pbms_creative_work_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pbms_creative_work_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pbms_extension_programs_forms" (
    "entry_id" bigint NOT NULL,
    "contributing_unit" "text",
    "academic_degree" "text",
    "no_of_beneficiary_groups" "text",
    "majority_share_funding" "text"
);


ALTER TABLE "public"."pbms_extension_programs_forms" OWNER TO "postgres";


ALTER TABLE "public"."pbms_extension_programs_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pbms_extension_programs_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pbms_oral_forms" (
    "entry_id" bigint NOT NULL,
    "linked_research" "text",
    "conference_title" "text",
    "organizer_name" "text",
    "conference_location" "text",
    "venue" "text",
    "conference_start_date" "date",
    "conference_end_date" "date",
    "presentation_date" "date"
);


ALTER TABLE "public"."pbms_oral_forms" OWNER TO "postgres";


ALTER TABLE "public"."pbms_oral_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pbms_oral_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pbms_other_accomplishments_forms" (
    "entry_id" bigint NOT NULL,
    "sub_type" "text"
);


ALTER TABLE "public"."pbms_other_accomplishments_forms" OWNER TO "postgres";


ALTER TABLE "public"."pbms_other_accomplishments_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pbms_other_accomplishments_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pbms_partnerships_forms" (
    "entry_id" bigint NOT NULL,
    "contributing_unit" "text",
    "partner_stakeholder_name" "text",
    "stakeholder_category" "text",
    "partnership_agreement_type" "text",
    "partnership_effectivity_start_date" "date",
    "partnership_effectivity_end_date" "date",
    "partnership_agreement" "text"
);


ALTER TABLE "public"."pbms_partnerships_forms" OWNER TO "postgres";


ALTER TABLE "public"."pbms_partnerships_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pbms_partnerships_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pbms_patents_forms" (
    "entry_id" bigint NOT NULL,
    "linked_research" "text",
    "patent_title" "text",
    "patent_type" "text",
    "application_no" numeric,
    "inventor_name" "text",
    "applicant_name" "text",
    "publication_date" "date",
    "grant_date" "date",
    "registration_no" numeric,
    "commercial_product_name" "text",
    "research_utilization_output" "text"
);


ALTER TABLE "public"."pbms_patents_forms" OWNER TO "postgres";


ALTER TABLE "public"."pbms_patents_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pbms_patents_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pbms_publication_forms" (
    "form_id" bigint NOT NULL,
    "publisher_name" "text",
    "publisher_type" "text",
    "publisher_location" "text",
    "editor_name" "text",
    "volume_issue_no" "text",
    "doi" "text",
    "isbn" "text",
    "number_of_citation" "text",
    "utilization_proof" "text"
);


ALTER TABLE "public"."pbms_publication_forms" OWNER TO "postgres";


ALTER TABLE "public"."pbms_publication_forms" ALTER COLUMN "form_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pbms_publication_forms_form_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pbms_research_forms" (
    "entry_id" bigint NOT NULL,
    "contributing_unit" "text",
    "original_timeframe_months" smallint,
    "majority_source_of_funds" "text"
);


ALTER TABLE "public"."pbms_research_forms" OWNER TO "postgres";


ALTER TABLE "public"."pbms_research_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pbms_research_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pbms_trainings_forms" (
    "entry_id" bigint NOT NULL,
    "contributing_unit" "text",
    "special_notes_schedule" "text",
    "training_hours_required" smallint,
    "total_trainees_number" integer,
    "majority_share_funding" "text",
    "sample_size" integer,
    "no_of_responses_poor" smallint,
    "no_of_responses_fair" smallint,
    "no_of_responses_satisfactory" smallint,
    "no_of_responses_outsanding" smallint,
    "part_extension_program" "text",
    "related_extension_program_title" "text"
);


ALTER TABLE "public"."pbms_trainings_forms" OWNER TO "postgres";


ALTER TABLE "public"."pbms_trainings_forms" ALTER COLUMN "entry_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pbms_trainings_forms_entry_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."reviews" (
    "reviews_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "review_date" "date",
    "status" "date",
    "remarks" "text",
    "report_id" bigint,
    "reviewed_by" bigint
);


ALTER TABLE "public"."reviews" OWNER TO "postgres";


ALTER TABLE "public"."reviews" ALTER COLUMN "reviews_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."reviews_reviews_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."supporting_documents" (
    "document_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "file_name" "text",
    "entry_id" bigint
);


ALTER TABLE "public"."supporting_documents" OWNER TO "postgres";


ALTER TABLE "public"."supporting_documents" ALTER COLUMN "document_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."supporting_documents_document_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."accomplishment_entries"
    ADD CONSTRAINT "accomplishment_entries_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."accomplishment_reports"
    ADD CONSTRAINT "accomplishment_reports_pkey" PRIMARY KEY ("report_id");



ALTER TABLE ONLY "public"."departments"
    ADD CONSTRAINT "department_pkey" PRIMARY KEY ("department_id");



ALTER TABLE ONLY "public"."export_records"
    ADD CONSTRAINT "export_records_pkey" PRIMARY KEY ("export_id");



ALTER TABLE ONLY "public"."faculties"
    ADD CONSTRAINT "faculties_pkey" PRIMARY KEY ("faculty_id");



ALTER TABLE ONLY "public"."form_types"
    ADD CONSTRAINT "form_types_pkey" PRIMARY KEY ("form_type_id");



ALTER TABLE ONLY "public"."isip_authorship_forms"
    ADD CONSTRAINT "isip_authorship_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."isip_awards_forms"
    ADD CONSTRAINT "isip_awards_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."isip_creative_work_forms"
    ADD CONSTRAINT "isip_creative_work_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."isip_extension_programs_forms"
    ADD CONSTRAINT "isip_extension_programs_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."isip_oral_forms"
    ADD CONSTRAINT "isip_oral_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."isip_other_accomplishments_forms"
    ADD CONSTRAINT "isip_other_accomplishments_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."isip_partnership_forms"
    ADD CONSTRAINT "isip_partnership_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."isip_patents_forms"
    ADD CONSTRAINT "isip_patents_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."isip_publication_forms"
    ADD CONSTRAINT "isip_publication_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."isip_research_forms"
    ADD CONSTRAINT "isip_research_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."isip_trainings_forms"
    ADD CONSTRAINT "isip_trainings_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."pbms_creative_work_forms"
    ADD CONSTRAINT "pbms_creative_work_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."pbms_extension_programs_forms"
    ADD CONSTRAINT "pbms_extension_programs_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."pbms_oral_forms"
    ADD CONSTRAINT "pbms_oral_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."pbms_other_accomplishments_forms"
    ADD CONSTRAINT "pbms_other_accomplishments_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."pbms_partnerships_forms"
    ADD CONSTRAINT "pbms_partnerships_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."pbms_patents_forms"
    ADD CONSTRAINT "pbms_patents_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."pbms_publication_forms"
    ADD CONSTRAINT "pbms_publication_forms_pkey" PRIMARY KEY ("form_id");



ALTER TABLE ONLY "public"."pbms_research_forms"
    ADD CONSTRAINT "pbms_research_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."pbms_trainings_forms"
    ADD CONSTRAINT "pbms_trainings_forms_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_pkey" PRIMARY KEY ("reviews_id");



ALTER TABLE ONLY "public"."supporting_documents"
    ADD CONSTRAINT "supporting_documents_pkey" PRIMARY KEY ("document_id");



ALTER TABLE ONLY "public"."accomplishment_entries"
    ADD CONSTRAINT "accomplishment_entries_form_type_id_fkey" FOREIGN KEY ("form_type_id") REFERENCES "public"."form_types"("form_type_id");



ALTER TABLE ONLY "public"."accomplishment_entries"
    ADD CONSTRAINT "accomplishment_entries_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "public"."accomplishment_reports"("report_id");



ALTER TABLE ONLY "public"."accomplishment_reports"
    ADD CONSTRAINT "accomplishment_reports_faculty_id_fkey" FOREIGN KEY ("faculty_id") REFERENCES "public"."faculties"("faculty_id");



ALTER TABLE ONLY "public"."export_records"
    ADD CONSTRAINT "export_records_generated_by_fkey" FOREIGN KEY ("generated_by") REFERENCES "public"."faculties"("faculty_id");



ALTER TABLE ONLY "public"."faculties"
    ADD CONSTRAINT "faculties_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("department_id");



ALTER TABLE ONLY "public"."isip_awards_forms"
    ADD CONSTRAINT "isip_awards_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."isip_creative_work_forms"
    ADD CONSTRAINT "isip_creative_work_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."isip_extension_programs_forms"
    ADD CONSTRAINT "isip_extension_programs_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."isip_oral_forms"
    ADD CONSTRAINT "isip_oral_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."isip_other_accomplishments_forms"
    ADD CONSTRAINT "isip_other_accomplishments_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."isip_partnership_forms"
    ADD CONSTRAINT "isip_partnership_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."isip_patents_forms"
    ADD CONSTRAINT "isip_patents_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."isip_publication_forms"
    ADD CONSTRAINT "isip_publication_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."isip_research_forms"
    ADD CONSTRAINT "isip_research_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."isip_trainings_forms"
    ADD CONSTRAINT "isip_trainings_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."pbms_creative_work_forms"
    ADD CONSTRAINT "pbms_creative_work_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."pbms_extension_programs_forms"
    ADD CONSTRAINT "pbms_extension_programs_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."pbms_oral_forms"
    ADD CONSTRAINT "pbms_oral_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."pbms_other_accomplishments_forms"
    ADD CONSTRAINT "pbms_other_accomplishments_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."pbms_partnerships_forms"
    ADD CONSTRAINT "pbms_partnerships_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."pbms_patents_forms"
    ADD CONSTRAINT "pbms_patents_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."pbms_publication_forms"
    ADD CONSTRAINT "pbms_publication_forms_form_id_fkey" FOREIGN KEY ("form_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."pbms_research_forms"
    ADD CONSTRAINT "pbms_research_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."pbms_trainings_forms"
    ADD CONSTRAINT "pbms_trainings_forms_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "public"."accomplishment_reports"("report_id");



ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "public"."faculties"("faculty_id");



ALTER TABLE ONLY "public"."supporting_documents"
    ADD CONSTRAINT "supporting_documents_entry_id_fkey" FOREIGN KEY ("entry_id") REFERENCES "public"."accomplishment_entries"("entry_id");



ALTER TABLE "public"."accomplishment_entries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."accomplishment_reports" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."departments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."export_records" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."faculties" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."form_types" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."isip_authorship_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."isip_awards_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."isip_creative_work_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."isip_extension_programs_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."isip_oral_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."isip_other_accomplishments_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."isip_partnership_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."isip_patents_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."isip_publication_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."isip_research_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."isip_trainings_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pbms_creative_work_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pbms_extension_programs_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pbms_oral_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pbms_other_accomplishments_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pbms_partnerships_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pbms_patents_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pbms_publication_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pbms_research_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pbms_trainings_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."reviews" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."supporting_documents" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT ALL ON TABLE "public"."accomplishment_entries" TO "anon";
GRANT ALL ON TABLE "public"."accomplishment_entries" TO "authenticated";
GRANT ALL ON TABLE "public"."accomplishment_entries" TO "service_role";



GRANT ALL ON TABLE "public"."accomplishment_reports" TO "anon";
GRANT ALL ON TABLE "public"."accomplishment_reports" TO "authenticated";
GRANT ALL ON TABLE "public"."accomplishment_reports" TO "service_role";



GRANT ALL ON SEQUENCE "public"."accomplishment_entries_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."accomplishment_entries_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."accomplishment_entries_entry_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."accomplishment_entries_entry_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."accomplishment_entries_entry_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."accomplishment_entries_entry_id_seq1" TO "service_role";



GRANT ALL ON TABLE "public"."departments" TO "anon";
GRANT ALL ON TABLE "public"."departments" TO "authenticated";
GRANT ALL ON TABLE "public"."departments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."department_department_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."department_department_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."department_department_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."export_records" TO "anon";
GRANT ALL ON TABLE "public"."export_records" TO "authenticated";
GRANT ALL ON TABLE "public"."export_records" TO "service_role";



GRANT ALL ON SEQUENCE "public"."export_records_export_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."export_records_export_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."export_records_export_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."faculties" TO "anon";
GRANT ALL ON TABLE "public"."faculties" TO "authenticated";
GRANT ALL ON TABLE "public"."faculties" TO "service_role";



GRANT ALL ON SEQUENCE "public"."faculties_faculty_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."faculties_faculty_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."faculties_faculty_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."form_types" TO "anon";
GRANT ALL ON TABLE "public"."form_types" TO "authenticated";
GRANT ALL ON TABLE "public"."form_types" TO "service_role";



GRANT ALL ON SEQUENCE "public"."form_types_form_type_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."form_types_form_type_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."form_types_form_type_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."isip_authorship_forms" TO "anon";
GRANT ALL ON TABLE "public"."isip_authorship_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."isip_authorship_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."isip_authorship_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."isip_authorship_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."isip_authorship_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."isip_awards_forms" TO "anon";
GRANT ALL ON TABLE "public"."isip_awards_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."isip_awards_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."isip_awards_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."isip_awards_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."isip_awards_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."isip_creative_work_forms" TO "anon";
GRANT ALL ON TABLE "public"."isip_creative_work_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."isip_creative_work_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."isip_creative_work_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."isip_creative_work_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."isip_creative_work_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."isip_extension_programs_forms" TO "anon";
GRANT ALL ON TABLE "public"."isip_extension_programs_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."isip_extension_programs_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."isip_extension_programs_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."isip_extension_programs_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."isip_extension_programs_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."isip_oral_forms" TO "anon";
GRANT ALL ON TABLE "public"."isip_oral_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."isip_oral_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."isip_oral_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."isip_oral_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."isip_oral_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."isip_other_accomplishments_forms" TO "anon";
GRANT ALL ON TABLE "public"."isip_other_accomplishments_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."isip_other_accomplishments_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."isip_other_accomplishments_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."isip_other_accomplishments_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."isip_other_accomplishments_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."isip_partnership_forms" TO "anon";
GRANT ALL ON TABLE "public"."isip_partnership_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."isip_partnership_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."isip_partnership_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."isip_partnership_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."isip_partnership_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."isip_patents_forms" TO "anon";
GRANT ALL ON TABLE "public"."isip_patents_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."isip_patents_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."isip_patents_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."isip_patents_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."isip_patents_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."isip_publication_forms" TO "anon";
GRANT ALL ON TABLE "public"."isip_publication_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."isip_publication_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."isip_publications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."isip_publications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."isip_publications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."isip_research_forms" TO "anon";
GRANT ALL ON TABLE "public"."isip_research_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."isip_research_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."isip_research_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."isip_research_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."isip_research_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."isip_trainings_forms" TO "anon";
GRANT ALL ON TABLE "public"."isip_trainings_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."isip_trainings_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."isip_trainings_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."isip_trainings_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."isip_trainings_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pbms_creative_work_forms" TO "anon";
GRANT ALL ON TABLE "public"."pbms_creative_work_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."pbms_creative_work_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pbms_creative_work_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pbms_creative_work_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pbms_creative_work_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pbms_extension_programs_forms" TO "anon";
GRANT ALL ON TABLE "public"."pbms_extension_programs_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."pbms_extension_programs_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pbms_extension_programs_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pbms_extension_programs_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pbms_extension_programs_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pbms_oral_forms" TO "anon";
GRANT ALL ON TABLE "public"."pbms_oral_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."pbms_oral_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pbms_oral_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pbms_oral_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pbms_oral_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pbms_other_accomplishments_forms" TO "anon";
GRANT ALL ON TABLE "public"."pbms_other_accomplishments_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."pbms_other_accomplishments_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pbms_other_accomplishments_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pbms_other_accomplishments_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pbms_other_accomplishments_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pbms_partnerships_forms" TO "anon";
GRANT ALL ON TABLE "public"."pbms_partnerships_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."pbms_partnerships_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pbms_partnerships_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pbms_partnerships_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pbms_partnerships_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pbms_patents_forms" TO "anon";
GRANT ALL ON TABLE "public"."pbms_patents_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."pbms_patents_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pbms_patents_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pbms_patents_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pbms_patents_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pbms_publication_forms" TO "anon";
GRANT ALL ON TABLE "public"."pbms_publication_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."pbms_publication_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pbms_publication_forms_form_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pbms_publication_forms_form_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pbms_publication_forms_form_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pbms_research_forms" TO "anon";
GRANT ALL ON TABLE "public"."pbms_research_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."pbms_research_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pbms_research_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pbms_research_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pbms_research_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pbms_trainings_forms" TO "anon";
GRANT ALL ON TABLE "public"."pbms_trainings_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."pbms_trainings_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pbms_trainings_forms_entry_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pbms_trainings_forms_entry_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pbms_trainings_forms_entry_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."reviews" TO "anon";
GRANT ALL ON TABLE "public"."reviews" TO "authenticated";
GRANT ALL ON TABLE "public"."reviews" TO "service_role";



GRANT ALL ON SEQUENCE "public"."reviews_reviews_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reviews_reviews_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reviews_reviews_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."supporting_documents" TO "anon";
GRANT ALL ON TABLE "public"."supporting_documents" TO "authenticated";
GRANT ALL ON TABLE "public"."supporting_documents" TO "service_role";



GRANT ALL ON SEQUENCE "public"."supporting_documents_document_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."supporting_documents_document_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."supporting_documents_document_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


