drop policy "Verified users can delete accomplishment_entries" on "public"."accomplishment_entries";
drop policy "Verified users can insert accomplishment_entries" on "public"."accomplishment_entries";
drop policy "Verified users can read accomplishment_entries" on "public"."accomplishment_entries";
drop policy "Verified users can update accomplishment_entries" on "public"."accomplishment_entries";
revoke delete on table "public"."accomplishment_entries" from "anon";
revoke insert on table "public"."accomplishment_entries" from "anon";
revoke references on table "public"."accomplishment_entries" from "anon";
revoke select on table "public"."accomplishment_entries" from "anon";
revoke trigger on table "public"."accomplishment_entries" from "anon";
revoke truncate on table "public"."accomplishment_entries" from "anon";
revoke update on table "public"."accomplishment_entries" from "anon";
revoke delete on table "public"."accomplishment_entries" from "authenticated";
revoke insert on table "public"."accomplishment_entries" from "authenticated";
revoke references on table "public"."accomplishment_entries" from "authenticated";
revoke select on table "public"."accomplishment_entries" from "authenticated";
revoke trigger on table "public"."accomplishment_entries" from "authenticated";
revoke truncate on table "public"."accomplishment_entries" from "authenticated";
revoke update on table "public"."accomplishment_entries" from "authenticated";
revoke delete on table "public"."accomplishment_entries" from "service_role";
revoke insert on table "public"."accomplishment_entries" from "service_role";
revoke references on table "public"."accomplishment_entries" from "service_role";
revoke select on table "public"."accomplishment_entries" from "service_role";
revoke trigger on table "public"."accomplishment_entries" from "service_role";
revoke truncate on table "public"."accomplishment_entries" from "service_role";
revoke update on table "public"."accomplishment_entries" from "service_role";
alter table "public"."accomplishment_entries" drop constraint "accomplishment_entries_form_type_id_fkey";
alter table "public"."accomplishment_entries" drop constraint "accomplishment_entries_report_id_fkey";
alter table "public"."isip_authorship_forms" drop constraint "isip_authorship_forms_entry_id_fkey";
alter table "public"."isip_awards_forms" drop constraint "isip_awards_forms_entry_id_fkey";
alter table "public"."isip_creative_work_forms" drop constraint "isip_creative_work_forms_entry_id_fkey";
alter table "public"."isip_extension_programs_forms" drop constraint "isip_extension_programs_forms_entry_id_fkey";
alter table "public"."isip_oral_forms" drop constraint "isip_oral_forms_entry_id_fkey";
alter table "public"."isip_other_accomplishments_forms" drop constraint "isip_other_accomplishments_forms_entry_id_fkey";
alter table "public"."isip_partnership_forms" drop constraint "isip_partnership_forms_entry_id_fkey";
alter table "public"."isip_patents_forms" drop constraint "isip_patents_forms_entry_id_fkey";
alter table "public"."isip_publication_forms" drop constraint "isip_publication_forms_entry_id_fkey";
alter table "public"."isip_research_forms" drop constraint "isip_research_forms_entry_id_fkey";
alter table "public"."isip_trainings_forms" drop constraint "isip_trainings_forms_entry_id_fkey";
alter table "public"."pbms_creative_work_forms" drop constraint "pbms_creative_work_forms_entry_id_fkey";
alter table "public"."pbms_extension_programs_forms" drop constraint "pbms_extension_programs_forms_entry_id_fkey";
alter table "public"."pbms_oral_forms" drop constraint "pbms_oral_forms_entry_id_fkey";
alter table "public"."pbms_other_accomplishments_forms" drop constraint "pbms_other_accomplishments_forms_entry_id_fkey";
alter table "public"."pbms_partnerships_forms" drop constraint "pbms_partnerships_forms_entry_id_fkey";
alter table "public"."pbms_patents_forms" drop constraint "pbms_patents_forms_entry_id_fkey";
alter table "public"."pbms_publication_forms" drop constraint "pbms_publication_forms_entry_id_fkey";
alter table "public"."pbms_research_forms" drop constraint "pbms_research_forms_entry_id_fkey";
alter table "public"."pbms_trainings_forms" drop constraint "pbms_trainings_forms_entry_id_fkey";
alter table "public"."supporting_documents" drop constraint "supporting_documents_entry_id_fkey";
alter table "public"."accomplishment_entries" drop constraint "accomplishment_entries_pkey";
drop index if exists "public"."accomplishment_entries_pkey";
drop table "public"."accomplishment_entries";
create table "public"."forms" (
    "entry_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text,
    "description" text,
    "author" text,
    "report_id" bigint,
    "form_type_id" bigint
      );
alter table "public"."forms" enable row level security;
alter table "public"."users" alter column "role" set default '''''''admin''''::text'::text;
CREATE UNIQUE INDEX accomplishment_entries_pkey ON public.forms USING btree (entry_id);
alter table "public"."forms" add constraint "accomplishment_entries_pkey" PRIMARY KEY using index "accomplishment_entries_pkey";
alter table "public"."forms" add constraint "accomplishment_entries_form_type_id_fkey" FOREIGN KEY (form_type_id) REFERENCES public.form_types(form_type_id) not valid;
alter table "public"."forms" validate constraint "accomplishment_entries_form_type_id_fkey";
alter table "public"."forms" add constraint "accomplishment_entries_report_id_fkey" FOREIGN KEY (report_id) REFERENCES public.accomplishment_reports(report_id) not valid;
alter table "public"."forms" validate constraint "accomplishment_entries_report_id_fkey";
alter table "public"."isip_authorship_forms" add constraint "isip_authorship_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."isip_authorship_forms" validate constraint "isip_authorship_forms_entry_id_fkey";
alter table "public"."isip_awards_forms" add constraint "isip_awards_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."isip_awards_forms" validate constraint "isip_awards_forms_entry_id_fkey";
alter table "public"."isip_creative_work_forms" add constraint "isip_creative_work_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."isip_creative_work_forms" validate constraint "isip_creative_work_forms_entry_id_fkey";
alter table "public"."isip_extension_programs_forms" add constraint "isip_extension_programs_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."isip_extension_programs_forms" validate constraint "isip_extension_programs_forms_entry_id_fkey";
alter table "public"."isip_oral_forms" add constraint "isip_oral_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."isip_oral_forms" validate constraint "isip_oral_forms_entry_id_fkey";
alter table "public"."isip_other_accomplishments_forms" add constraint "isip_other_accomplishments_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."isip_other_accomplishments_forms" validate constraint "isip_other_accomplishments_forms_entry_id_fkey";
alter table "public"."isip_partnership_forms" add constraint "isip_partnership_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."isip_partnership_forms" validate constraint "isip_partnership_forms_entry_id_fkey";
alter table "public"."isip_patents_forms" add constraint "isip_patents_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."isip_patents_forms" validate constraint "isip_patents_forms_entry_id_fkey";
alter table "public"."isip_publication_forms" add constraint "isip_publication_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."isip_publication_forms" validate constraint "isip_publication_forms_entry_id_fkey";
alter table "public"."isip_research_forms" add constraint "isip_research_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."isip_research_forms" validate constraint "isip_research_forms_entry_id_fkey";
alter table "public"."isip_trainings_forms" add constraint "isip_trainings_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."isip_trainings_forms" validate constraint "isip_trainings_forms_entry_id_fkey";
alter table "public"."pbms_creative_work_forms" add constraint "pbms_creative_work_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."pbms_creative_work_forms" validate constraint "pbms_creative_work_forms_entry_id_fkey";
alter table "public"."pbms_extension_programs_forms" add constraint "pbms_extension_programs_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."pbms_extension_programs_forms" validate constraint "pbms_extension_programs_forms_entry_id_fkey";
alter table "public"."pbms_oral_forms" add constraint "pbms_oral_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."pbms_oral_forms" validate constraint "pbms_oral_forms_entry_id_fkey";
alter table "public"."pbms_other_accomplishments_forms" add constraint "pbms_other_accomplishments_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."pbms_other_accomplishments_forms" validate constraint "pbms_other_accomplishments_forms_entry_id_fkey";
alter table "public"."pbms_partnerships_forms" add constraint "pbms_partnerships_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."pbms_partnerships_forms" validate constraint "pbms_partnerships_forms_entry_id_fkey";
alter table "public"."pbms_patents_forms" add constraint "pbms_patents_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."pbms_patents_forms" validate constraint "pbms_patents_forms_entry_id_fkey";
alter table "public"."pbms_publication_forms" add constraint "pbms_publication_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."pbms_publication_forms" validate constraint "pbms_publication_forms_entry_id_fkey";
alter table "public"."pbms_research_forms" add constraint "pbms_research_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."pbms_research_forms" validate constraint "pbms_research_forms_entry_id_fkey";
alter table "public"."pbms_trainings_forms" add constraint "pbms_trainings_forms_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."pbms_trainings_forms" validate constraint "pbms_trainings_forms_entry_id_fkey";
alter table "public"."supporting_documents" add constraint "supporting_documents_entry_id_fkey" FOREIGN KEY (entry_id) REFERENCES public.forms(entry_id) not valid;
alter table "public"."supporting_documents" validate constraint "supporting_documents_entry_id_fkey";
grant delete on table "public"."forms" to "anon";
grant insert on table "public"."forms" to "anon";
grant references on table "public"."forms" to "anon";
grant select on table "public"."forms" to "anon";
grant trigger on table "public"."forms" to "anon";
grant truncate on table "public"."forms" to "anon";
grant update on table "public"."forms" to "anon";
grant delete on table "public"."forms" to "authenticated";
grant insert on table "public"."forms" to "authenticated";
grant references on table "public"."forms" to "authenticated";
grant select on table "public"."forms" to "authenticated";
grant trigger on table "public"."forms" to "authenticated";
grant truncate on table "public"."forms" to "authenticated";
grant update on table "public"."forms" to "authenticated";
grant delete on table "public"."forms" to "service_role";
grant insert on table "public"."forms" to "service_role";
grant references on table "public"."forms" to "service_role";
grant select on table "public"."forms" to "service_role";
grant trigger on table "public"."forms" to "service_role";
grant truncate on table "public"."forms" to "service_role";
grant update on table "public"."forms" to "service_role";
create policy "Verified users can delete accomplishment_entries"
  on "public"."forms"
  as permissive
  for delete
  to authenticated
using (public.has_verified_profile());
create policy "Verified users can insert accomplishment_entries"
  on "public"."forms"
  as permissive
  for insert
  to authenticated
with check (public.has_verified_profile());
create policy "Verified users can read accomplishment_entries"
  on "public"."forms"
  as permissive
  for select
  to authenticated
using (public.has_verified_profile());
create policy "Verified users can update accomplishment_entries"
  on "public"."forms"
  as permissive
  for update
  to authenticated
using (public.has_verified_profile())
with check (public.has_verified_profile());
