-- Align Form F-H schema with frontend Supabase insert payloads.

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'form_f_awards_and_grants'
      AND column_name = 'award'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'form_f_awards_and_grants'
      AND column_name = 'award_grant_title'
  ) THEN
    ALTER TABLE public.form_f_awards_and_grants
      RENAME COLUMN award TO award_grant_title;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'form_f_awards_and_grants'
      AND column_name = 'source'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'form_f_awards_and_grants'
      AND column_name = 'source_awarding_body'
  ) THEN
    ALTER TABLE public.form_f_awards_and_grants
      RENAME COLUMN source TO source_awarding_body;
  END IF;
END
$$;

ALTER TABLE public.form_f_awards_and_grants
  DROP CONSTRAINT IF EXISTS form_f_awards_and_grants_entry_id_fkey,
  ADD COLUMN IF NOT EXISTS submitted_by text,
  ADD COLUMN IF NOT EXISTS type text,
  ADD COLUMN IF NOT EXISTS details text,
  ADD COLUMN IF NOT EXISTS start_date date,
  ADD COLUMN IF NOT EXISTS end_date date,
  ADD COLUMN IF NOT EXISTS attachments jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS remarks text,
  ADD COLUMN IF NOT EXISTS related_kras text;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'form_f_awards_and_grants'
      AND column_name = 'attachments'
      AND data_type = 'text'
  ) THEN
    ALTER TABLE public.form_f_awards_and_grants
      ALTER COLUMN attachments TYPE jsonb
      USING CASE
        WHEN attachments IS NULL OR btrim(attachments) = '' THEN '[]'::jsonb
        WHEN pg_input_is_valid(attachments, 'jsonb') THEN attachments::jsonb
        ELSE to_jsonb(attachments)
      END;
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.form_g_trainings (
  entry_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submitted_by text,
  contributing_unit text,
  type_of_activity text,
  title text,
  venue text,
  start_date date,
  end_date date,
  special_notes text,
  training_hours integer,
  total_trainees integer,
  funding_source text,
  sample_size integer,
  responses_poor integer,
  responses_fair integer,
  responses_satisfactory integer,
  responses_very_satisfactory integer,
  responses_outstanding integer,
  is_part_of_extension_program boolean,
  related_extension_program text,
  attachments jsonb DEFAULT '[]'::jsonb,
  remarks text,
  related_kras text
);

ALTER TABLE public.form_g_trainings
  ADD COLUMN IF NOT EXISTS submitted_by text,
  ADD COLUMN IF NOT EXISTS contributing_unit text,
  ADD COLUMN IF NOT EXISTS type_of_activity text,
  ADD COLUMN IF NOT EXISTS title text,
  ADD COLUMN IF NOT EXISTS venue text,
  ADD COLUMN IF NOT EXISTS start_date date,
  ADD COLUMN IF NOT EXISTS end_date date,
  ADD COLUMN IF NOT EXISTS special_notes text,
  ADD COLUMN IF NOT EXISTS training_hours integer,
  ADD COLUMN IF NOT EXISTS total_trainees integer,
  ADD COLUMN IF NOT EXISTS funding_source text,
  ADD COLUMN IF NOT EXISTS sample_size integer,
  ADD COLUMN IF NOT EXISTS responses_poor integer,
  ADD COLUMN IF NOT EXISTS responses_fair integer,
  ADD COLUMN IF NOT EXISTS responses_satisfactory integer,
  ADD COLUMN IF NOT EXISTS responses_very_satisfactory integer,
  ADD COLUMN IF NOT EXISTS responses_outstanding integer,
  ADD COLUMN IF NOT EXISTS is_part_of_extension_program boolean,
  ADD COLUMN IF NOT EXISTS related_extension_program text,
  ADD COLUMN IF NOT EXISTS attachments jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS remarks text,
  ADD COLUMN IF NOT EXISTS related_kras text;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'form_g_trainings'
      AND column_name = 'attachments'
      AND data_type = 'text'
  ) THEN
    ALTER TABLE public.form_g_trainings
      ALTER COLUMN attachments TYPE jsonb
      USING CASE
        WHEN attachments IS NULL OR btrim(attachments) = '' THEN '[]'::jsonb
        WHEN pg_input_is_valid(attachments, 'jsonb') THEN attachments::jsonb
        ELSE to_jsonb(attachments)
      END;
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.form_h_extension_programs (
  entry_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submitted_by text,
  contributing_unit text,
  title text,
  training_courses boolean,
  technical_advisory_service boolean,
  information_dissemination boolean,
  consultancy boolean,
  community_outreach boolean,
  technology_transfer boolean,
  organizing boolean,
  academic_degree_programs text,
  scope_of_work text,
  start_date date,
  end_date date,
  target_beneficiary text,
  number_of_beneficiaries integer,
  funding_source text,
  program_documents jsonb DEFAULT '[]'::jsonb,
  remarks text
);

ALTER TABLE public.form_h_extension_programs
  ADD COLUMN IF NOT EXISTS submitted_by text,
  ADD COLUMN IF NOT EXISTS contributing_unit text,
  ADD COLUMN IF NOT EXISTS title text,
  ADD COLUMN IF NOT EXISTS training_courses boolean,
  ADD COLUMN IF NOT EXISTS technical_advisory_service boolean,
  ADD COLUMN IF NOT EXISTS information_dissemination boolean,
  ADD COLUMN IF NOT EXISTS consultancy boolean,
  ADD COLUMN IF NOT EXISTS community_outreach boolean,
  ADD COLUMN IF NOT EXISTS technology_transfer boolean,
  ADD COLUMN IF NOT EXISTS organizing boolean,
  ADD COLUMN IF NOT EXISTS academic_degree_programs text,
  ADD COLUMN IF NOT EXISTS scope_of_work text,
  ADD COLUMN IF NOT EXISTS start_date date,
  ADD COLUMN IF NOT EXISTS end_date date,
  ADD COLUMN IF NOT EXISTS target_beneficiary text,
  ADD COLUMN IF NOT EXISTS number_of_beneficiaries integer,
  ADD COLUMN IF NOT EXISTS funding_source text,
  ADD COLUMN IF NOT EXISTS program_documents jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS remarks text;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'form_h_extension_programs'
      AND column_name = 'program_documents'
      AND data_type = 'text'
  ) THEN
    ALTER TABLE public.form_h_extension_programs
      ALTER COLUMN program_documents TYPE jsonb
      USING CASE
        WHEN program_documents IS NULL OR btrim(program_documents) = '' THEN '[]'::jsonb
        WHEN pg_input_is_valid(program_documents, 'jsonb') THEN program_documents::jsonb
        ELSE to_jsonb(program_documents)
      END;
  END IF;
END
$$;

GRANT SELECT ON TABLE public.form_g_trainings TO anon;
GRANT SELECT ON TABLE public.form_h_extension_programs TO anon;
GRANT ALL ON TABLE public.form_g_trainings TO authenticated, service_role;
GRANT ALL ON TABLE public.form_h_extension_programs TO authenticated, service_role;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.sequences
    WHERE sequence_schema = 'public'
      AND sequence_name = 'form_g_trainings_entry_id_seq'
  ) THEN
    GRANT ALL ON SEQUENCE public.form_g_trainings_entry_id_seq TO authenticated, service_role;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.sequences
    WHERE sequence_schema = 'public'
      AND sequence_name = 'form_h_extension_programs_entry_id_seq'
  ) THEN
    GRANT ALL ON SEQUENCE public.form_h_extension_programs_entry_id_seq TO authenticated, service_role;
  END IF;
END
$$;

ALTER TABLE public.form_g_trainings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_h_extension_programs ENABLE ROW LEVEL SECURITY;
